services:
  postgres:
    container_name: postgres-hans
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: hans
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hans_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U hans -d hans_db']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - line

  redis:
    container_name: redis-hans
    image: redis/redis-stack:7.4.0-v8
    ports:
      - 6379:6379
      - 8888:8001
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - line

volumes:
  postgres_data:
  redis_data:

networks:
  line:
