CREATE TYPE "public"."user_settings_type" AS ENUM('timezone');--> statement-breakpoint
CREATE TABLE "command_usage" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "command_usage_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"guild_id" text,
	"command_name" text NOT NULL,
	"feature_name" text,
	"source" text DEFAULT 'slash' NOT NULL,
	"success" boolean DEFAULT true NOT NULL,
	"duration_ms" integer,
	"invoked_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "configs" (
	"id" integer PRIMARY KEY NOT NULL,
	"bot_id" text NOT NULL,
	"bot_guild_id" text,
	"activity_name" text,
	"activity_type" integer,
	"bot_dev_folder" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"discord_client_id" text,
	"name" text,
	"notify_channel_id" text,
	"perma_invite" text,
	"website" text,
	"monitoring_channel_id" text
);
--> statement-breakpoint
CREATE TABLE "guild_quests" (
	"id" uuid PRIMARY KEY NOT NULL,
	"guild_id" integer NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"question" text,
	"answer" text,
	"mode" text NOT NULL,
	"winners_count" integer,
	"reward" text NOT NULL,
	"reward_code" text,
	"channel_id" text NOT NULL,
	"thread_id" text,
	"message_id" text,
	"created_by" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expiration_date" timestamp with time zone NOT NULL,
	"is_claimed" boolean DEFAULT false NOT NULL,
	"is_pending_claim" boolean DEFAULT false NOT NULL,
	"winner" jsonb,
	"winners" jsonb,
	CONSTRAINT "guild_quests_mode_check" CHECK ("guild_quests"."mode" IN ('quiz', 'raffle'))
);
--> statement-breakpoint
CREATE TABLE "guilds" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "guilds_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"avatar" text,
	"name" text,
	"premium" boolean DEFAULT false,
	"created_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "guilds_guild_id_unique" UNIQUE("guild_id")
);
--> statement-breakpoint
CREATE TABLE "guilds_plugins" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "guilds_plugins_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"owner" text NOT NULL,
	"enabled" boolean NOT NULL,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "plugins" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "plugins_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"description" text NOT NULL,
	"enabled" boolean NOT NULL,
	"premium" boolean NOT NULL,
	"category" text DEFAULT 'miscellaneous' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "plugins_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "users_settings" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now(),
	"user_id" text NOT NULL,
	"metadata" jsonb,
	"type" "user_settings_type"
);
--> statement-breakpoint
ALTER TABLE "guild_quests" ADD CONSTRAINT "guild_quests_guild_id_guilds_id_fk" FOREIGN KEY ("guild_id") REFERENCES "public"."guilds"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "guilds_plugins" ADD CONSTRAINT "guilds_plugins_name_plugins_name_fk" FOREIGN KEY ("name") REFERENCES "public"."plugins"("name") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "guilds_plugins" ADD CONSTRAINT "guilds_plugins_owner_guilds_guild_id_fk" FOREIGN KEY ("owner") REFERENCES "public"."guilds"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_command_usage_guild_time" ON "command_usage" USING btree ("guild_id","invoked_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "idx_command_usage_command_time" ON "command_usage" USING btree ("command_name","invoked_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "idx_command_usage_guild_command" ON "command_usage" USING btree ("guild_id","command_name");--> statement-breakpoint
CREATE INDEX "idx_guild_quests_guild" ON "guild_quests" USING btree ("guild_id");--> statement-breakpoint
CREATE INDEX "idx_guilds_plugins_owner_name" ON "guilds_plugins" USING btree ("owner","name");--> statement-breakpoint
CREATE UNIQUE INDEX "users_settings_user_id_type_key" ON "users_settings" USING btree ("user_id","type");