CREATE TYPE "public"."user_settings_type" AS ENUM('timezone');--> statement-breakpoint
CREATE TABLE "configs" (
	"id" integer PRIMARY KEY NOT NULL,
	"bot_id" text NOT NULL,
	"bot_guild_id" text,
	"activity_name" text,
	"activity_type" integer,
	"bot_dev_folder" text,
	"created_at" text,
	"discord_client_id" text,
	"name" text,
	"notify_channel_id" text,
	"perma_invite" text,
	"website" text,
	"monitoring_channel_id" text
);
--> statement-breakpoint
CREATE TABLE "plugins" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "plugins_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text,
	"description" text,
	"enabled" boolean,
	"premium" boolean,
	"category" text DEFAULT 'miscellaneous',
	"created_at" text,
	CONSTRAINT "plugins_name_key" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "guilds" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "guilds_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"avatar" text,
	"name" text,
	"premium" boolean DEFAULT false,
	"created_at" text,
	CONSTRAINT "guilds_guild_id_key" UNIQUE("guild_id")
);
--> statement-breakpoint
CREATE TABLE "guilds_plugins" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "guilds_plugins_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text,
	"owner" text,
	"enabled" boolean,
	"metadata" jsonb,
	"created_at" text
);
--> statement-breakpoint
CREATE TABLE "guild_quests" (
	"id" uuid PRIMARY KEY NOT NULL,
	"guild_id" integer NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"question" text,
	"answer" text,
	"mode" text NOT NULL,
	"winners_count" integer,
	"reward" text NOT NULL,
	"reward_code" text,
	"channel_id" text NOT NULL,
	"thread_id" text,
	"message_id" text,
	"created_by" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expiration_date" timestamp with time zone NOT NULL,
	"is_claimed" boolean DEFAULT false NOT NULL,
	"is_pending_claim" boolean DEFAULT false NOT NULL,
	"winner" jsonb,
	"winners" jsonb,
	CONSTRAINT "guild_quests_guild_id_idx" UNIQUE("id","guild_id"),
	CONSTRAINT "guild_quests_mode_check" CHECK (mode = ANY (ARRAY['quiz'::text, 'raffle'::text]))
);
--> statement-breakpoint
CREATE TABLE "users_settings" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "users_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now(),
	"user_id" text NOT NULL,
	"metadata" jsonb,
	"type" "user_settings_type",
	CONSTRAINT "users_settings_pkey" PRIMARY KEY("id","user_id")
);
--> statement-breakpoint
ALTER TABLE "guilds_plugins" ADD CONSTRAINT "guilds_plugins_name_fkey" FOREIGN KEY ("name") REFERENCES "public"."plugins"("name") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "guilds_plugins" ADD CONSTRAINT "guilds_plugins_owner_fkey" FOREIGN KEY ("owner") REFERENCES "public"."guilds"("guild_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "guild_quests" ADD CONSTRAINT "guild_quests_guild_id_fkey" FOREIGN KEY ("guild_id") REFERENCES "public"."guilds"("id") ON DELETE cascade ON UPDATE no action;
